return {
  { import = "plugins.override.go" },
  { import = "plugins.override.fzf" },
  { import = "plugins.override.helm" },
  { import = "plugins.override.flash" },
  { import = "plugins.override.mason" },
  { import = "plugins.override.wilder" },
  { import = "plugins.override.zoxide" },
  { import = "plugins.override.codeium" },
  { import = "plugins.override.copilot" },
  { import = "plugins.override.lazygit" },
  { import = "plugins.override.conform" },
  { import = "plugins.override.diffview" },
  { import = "plugins.override.lspconfig" },
  { import = "plugins.override.neoscroll" },
  { import = "plugins.override.treesitter" },
  { import = "plugins.override.visual-multi" },
}
